name: CI

on:
  push:
  pull_request:

jobs:
  build-sample-app:
    runs-on: macos-15-intel

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build sample app
        run: |
          xcodebuild \
            -project SMPPaymentSampleApp.xcodeproj \
            -scheme SMPPaymentSampleApp \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath /tmp/SMPPaymentSampleApp-DerivedData \
            ONLY_ACTIVE_ARCH=YES \
            ARCHS=x86_64 \
            CODE_SIGNING_ALLOWED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            build
